---
- name: Prepare DC
  hosts:
    - dc
  roles:
    - role: trippsc2.ad.testing_domain_controller

- name: Prepare member server
  hosts:
    - windows_domain_members
  gather_facts: false
  roles:
    - role: trippsc2.ad.testing_win_member

- name: Prepare
  hosts:
    - subjects
  tasks:
    - name: Install MDT
      chocolatey.chocolatey.win_chocolatey:
        name:
          - windows-adk-all
          - mdt
        state: present

    - name: Create MDT Deployment Share
      trippsc2.mdt.deployment_share:
        mdt_share_path: "{{ dell_mdt_share_path }}"
        description: MDT Deployment Share
        unc_path: "\\\\{{ inventory_hostname | upper }}\\MDTShare$"
        state: present

    - name: Create SMB share
      ansible.windows.win_share:
        name: MDTShare$
        path: "{{ dell_mdt_share_path }}"
        full: Everyone
        caching_mode: None

    - name: Add permissions to MDT Deployment Share
      ansible.windows.win_acl:
        path: "{{ dell_mdt_share_path }}"
        user: vagrant
        rights: FullControl
        type: allow

    - name: Configure MDT Deployment Share settings
      trippsc2.mdt.deployment_share_settings:
        mdt_share_path: "{{ dell_mdt_share_path }}"
        x86:
          enabled: false
        x64:
          selection_profile: Nothing

    - name: Pre-create MDT directories to cleanup
      loop:
        - Out-of-Box Drivers\WinPE11\A00
        - Out-of-Box Drivers\WinPE10\A00
        - Out-of-Box Drivers\Windows 11\Dell Inc.\Latitude 5550\A00
        - Out-of-Box Drivers\Windows 11\Dell Inc.\OptiPlex Micro 7020\A00
        - Out-of-Box Drivers\Windows 11\Dell Inc.\XPS 17 9710\A00
        - Out-of-Box Drivers\Windows 10\Dell Inc.\Latitude 5550\A00
        - Out-of-Box Drivers\Windows 10\Dell Inc.\OptiPlex Micro 7020\A00
        - Out-of-Box Drivers\Windows 10\Dell Inc.\XPS 17 9710\A00
      trippsc2.mdt.directory:
        path: "{{ item }}"
        mdt_share_path: "{{ dell_mdt_share_path }}"
        state: present

    - name: Install Windows Deployment Services feature
      ansible.windows.win_feature:
        name:
          - WDS
        include_management_tools: true
        state: present

    - name: Initialize WDS
      trippsc2.windows.wds_initialize:
        remote_install_path: C:\RemoteInstall
        state: initialized
