---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: mdt_drivers
  description: This role manages Dell MDT drivers.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - community.windows
  - trippsc2.mdt
  - trippsc2.windows

dependencies:
  - role: trippsc2.windows.install_psgallery
